import Head from "next/head";

import Contact from "../components/Contact";
import Skills from "../components/Skills";
import Footer from "../components/Footer";

import { useState } from "react";

import Portfolio from "../components/Portfolio";

export default function Home() {
  const [displayPortfolio, setDisplayPortfolio] = useState(false);
  return (
    <div>
      <Head>
        <title>Jared Carver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Portfolio
        displayPortfolio={displayPortfolio}
        setDisplayPortfolio={setDisplayPortfolio}
      />

      <Skills />
      <Contact />
      <Footer
        displayPortfolio={displayPortfolio}
        setDisplayPortfolio={setDisplayPortfolio}
      />
    </div>
  );
}
