import Head from "next/head";

import Feature from "../components/Feature";

import MovieTitle from "../components/MovieTitle";
import AllProjects from "../components/AllProjects";
import Contact from "../components/Contact";
import Skills from "../components/Skills";
import Footer from "../components/Footer";

import { useState } from "react";

import Portfolio from "../components/Portfolio";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jared Carver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Portfolio />
      <Feature />
      <MovieTitle />
      <AllProjects />
      <Skills />
      <Contact />
      <Footer />
    </div>
  );
}
